apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: tax-calculator-pipeline
spec:
  tasks:
  - name: npminstall
    taskRef:
      name: npm-install

  - name: tests
    taskRef:
      name: jasmine-test

  - name: build
    taskRef:
      name: build-image
